name: deploy to k8s
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}"  > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Deploy to Kubernetes
        run: |
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
      - name: dispaly pods
        run: |
          kubectl get pods -n vacationapp
          kubectl get services -n vacationapp
          

        
